In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.8.0+cu126


In [2]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


In [3]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [5]:
scalar.item()

7

In [6]:
vector=torch.tensor([7,7])
vector

tensor([7, 7])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

In [9]:
Matrix = torch.tensor([[7,8],[9,10]])
Matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [10]:
Matrix.ndim

2

In [11]:
Matrix[0][1]

tensor(8)

In [12]:
Matrix.shape

torch.Size([2, 2])

In [13]:
Tensor=torch.tensor([[[1,2,3],[3,6,9],[2,4,5]]])
Tensor

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [14]:
Tensor.ndim

3

In [15]:
Tensor.shape

torch.Size([1, 3, 3])

In [16]:
Tensor[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

In [17]:
random_tensor= torch.rand(2,3,4)
random_tensor

tensor([[[0.6649, 0.3806, 0.4567, 0.6802],
         [0.2430, 0.6247, 0.6138, 0.4722],
         [0.6868, 0.5276, 0.0907, 0.2157]],

        [[0.7190, 0.8603, 0.4955, 0.7344],
         [0.6428, 0.9584, 0.6080, 0.1416],
         [0.0607, 0.3670, 0.6669, 0.4714]]])

In [18]:
random_tensor.shape

torch.Size([2, 3, 4])

In [19]:
random_tensor.ndim

3

In [20]:
random_image_size_tensor=torch.rand(size=(224,224,3)) #height , width , colour channel
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [21]:
zeros=torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [22]:
zeros*random_tensor

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [23]:
ones=torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [24]:
random_tensor.dtype

torch.float32

In [25]:
one_to_ten=torch.arange(start=0, end=11, step=1)
one_to_ten

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [26]:
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [27]:
float_32_tensor=torch.tensor([3.0,6.0,9.0], dtype=None , device=None, requires_grad=False)
float_32_tensor

tensor([3., 6., 9.])

In [28]:
float_32_tensor.dtype

torch.float32

In [29]:
float_16_tensor=float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [30]:
some_tensor=torch.rand(3,4)
some_tensor

tensor([[0.6231, 0.0446, 0.2498, 0.7773],
        [0.0153, 0.2722, 0.3975, 0.0325],
        [0.0708, 0.7377, 0.6770, 0.6873]])

In [31]:
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.size()}")
print(f"Device tensor is on: {some_tensor.device}")


tensor([[0.6231, 0.0446, 0.2498, 0.7773],
        [0.0153, 0.2722, 0.3975, 0.0325],
        [0.0708, 0.7377, 0.6770, 0.6873]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


In [32]:
tensor=torch.tensor([1,2,3])
tensor+100

tensor([101, 102, 103])

In [33]:
tensor

tensor([1, 2, 3])

In [34]:
tensor-10

tensor([-9, -8, -7])

In [35]:
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [36]:
torch.add(tensor,10)

tensor([11, 12, 13])

In [37]:
print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [38]:
torch.matmul(tensor, tensor)

tensor(14)

In [39]:
%%time
value=0
for i in range(len(tensor)):
  value+=tensor[i]*tensor[i]
value


CPU times: user 453 µs, sys: 909 µs, total: 1.36 ms
Wall time: 2.64 ms


tensor(14)

In [40]:
%%time
torch.matmul(tensor,tensor)

CPU times: user 630 µs, sys: 0 ns, total: 630 µs
Wall time: 869 µs


tensor(14)

In [41]:
tensor @ tensor

tensor(14)

In [42]:
torch.matmul(torch.rand(3,2), torch.rand(2,3))

tensor([[0.0802, 0.2691, 0.3171],
        [0.2103, 0.7695, 0.7521],
        [0.2580, 0.9276, 0.9434]])