In [2]:
import os
import math
import numpy as np
import time

import matplotlib.pyplot as plt
%matplotlib inline
from IPython.display import set_matplotlib_formats
set_matplotlib_formats('svg','pdf')
from matplotlib.colors import to_rgba
import seaborn as sns
sns.set()

from tqdm.notebook import tqdm

/tmp/ipython-input-1579109403.py:9: DeprecationWarning: `set_matplotlib_formats` is deprecated since IPython 7.23, directly use `matplotlib_inline.backend_inline.set_matplotlib_formats()`
  set_matplotlib_formats('svg','pdf')


In [3]:
import torch
print("using torch",torch.__version__)

using torch 2.8.0+cu126


In [4]:
torch.manual_seed(42)

In [5]:
x=torch.Tensor(2,3,4)
print(x)

tensor([[[4.8102e+32, 4.5312e-41, 4.7439e+32, 4.5312e-41],
         [5.9194e+32, 4.5312e-41, 5.9622e+32, 4.5312e-41],
         [4.7061e+32, 4.5312e-41, 4.5532e+32, 4.5312e-41]],

        [[4.7533e+32, 4.5312e-41, 4.8566e+32, 4.5312e-41],
         [4.6022e+32, 4.5312e-41, 5.4557e+32, 4.5312e-41],
         [4.8500e+32, 4.5312e-41, 5.7286e+32, 4.5312e-41]]])


In [6]:
x=torch.Tensor([[1,2],[3,4]])
print(x)

tensor([[1., 2.],
        [3., 4.]])


In [8]:
x=torch.rand(2,3,4)
print(x)

tensor([[[0.8823, 0.9150, 0.3829, 0.9593],
         [0.3904, 0.6009, 0.2566, 0.7936],
         [0.9408, 0.1332, 0.9346, 0.5936]],

        [[0.8694, 0.5677, 0.7411, 0.4294],
         [0.8854, 0.5739, 0.2666, 0.6274],
         [0.2696, 0.4414, 0.2969, 0.8317]]])


In [10]:
shape=x.shape
print("shape",x.shape)

size=x.size()
print("size:",size)

dim1 , dim2 , dim3 = x.size()
print("size", dim1, dim2 , dim3)

shape torch.Size([2, 3, 4])
size: torch.Size([2, 3, 4])
size 2 3 4


In [11]:
np_arr=np.array([[1,2],[3,4]])
tensor=torch.from_numpy(np_arr)

print("Numpy array:", np_arr)
print("pytorch tensor:",tensor)

Numpy array: [[1 2]
 [3 4]]
pytorch tensor: tensor([[1, 2],
        [3, 4]])


In [13]:
tensor=torch.arange(4)
np_arr=tensor.numpy()

print("Pytorch tensor: ", tensor)
print("Numpy array:", np_arr)

Pytorch tensor:  tensor([0, 1, 2, 3])
Numpy array: [0 1 2 3]


In [14]:
x1 = torch.rand(2,3)
x2= torch.rand(2,3)
y=x1+x2

print("x1",x1)
print("x2",x2)
print("y",y)

x1 tensor([[0.1053, 0.2695, 0.3588],
        [0.1994, 0.5472, 0.0062]])
x2 tensor([[0.9516, 0.0753, 0.8860],
        [0.5832, 0.3376, 0.8090]])
y tensor([[1.0569, 0.3448, 1.2448],
        [0.7826, 0.8848, 0.8151]])


In [15]:
x1=torch.rand(2,3)
x2=torch.rand(2,3)
print("X1 (before)",x1)
print("X2 (before)",x2)

x2.add_(x1)
print("x1(after)",x1)
print("x2(after)",x2)

X1 (before) tensor([[0.5779, 0.9040, 0.5547],
        [0.3423, 0.6343, 0.3644]])
X2 (before) tensor([[0.7104, 0.9464, 0.7890],
        [0.2814, 0.7886, 0.5895]])
x1(after) tensor([[0.5779, 0.9040, 0.5547],
        [0.3423, 0.6343, 0.3644]])
x2(after) tensor([[1.2884, 1.8504, 1.3437],
        [0.6237, 1.4230, 0.9539]])


In [17]:
x=torch.arange(6)
print("X",x)


X tensor([0, 1, 2, 3, 4, 5])


In [18]:
x=x.view(2,3)
print("X",x)

X tensor([[0, 1, 2],
        [3, 4, 5]])


In [19]:
x=x.permute(1,0)
print("X",x)

X tensor([[0, 3],
        [1, 4],
        [2, 5]])


In [23]:
x=torch.arange(6)
x=x.view(2,3)
print("X",x)

X tensor([[0, 1, 2],
        [3, 4, 5]])


In [25]:
w=torch.arange(9).view(3,3)
print("W",w)

W tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])


In [26]:
h=torch.matmul(x,w)
print("h",h)

h tensor([[15, 18, 21],
        [42, 54, 66]])


In [27]:
x=torch.arange(12).view(3,4)
print("X",x)

X tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])


In [28]:
print(x[:,1])

tensor([1, 5, 9])


In [29]:
print(x[0])

tensor([0, 1, 2, 3])


In [30]:
print(x[:2,-1])

tensor([3, 7])


In [31]:
print(x[1:3,:])

tensor([[ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
