In [1]:
import torch
import torch.nn as nn
import numpy as np

In [2]:
inputs = np.array([
    [73, 67, 43],
    [91, 88, 64],
    [87, 134, 58],
    [102, 43, 37],
    [69, 96, 70],
    [74, 66, 43],
    [91, 87, 65],
    [88, 134, 59],
    [101, 44, 37],
    [68, 96, 71],
    [73, 66, 44],
    [92, 87, 64],
    [87, 135, 57],
    [103, 43, 36],
    [68, 97, 70]
], dtype='float32')

targets = np.array([
    [56, 70],
    [81, 101],
    [119, 133],
    [22, 37],
    [103, 119],
    [57, 69],
    [80, 102],
    [118, 132],
    [21, 38],
    [104, 118],
    [57, 69],
    [82, 100],
    [118, 134],
    [20, 38],
    [102, 120]
], dtype='float32')


inputs=torch.from_numpy(inputs)
targets=torch.from_numpy(targets)



In [3]:
from torch.utils.data import TensorDataset
from torch.utils.data import DataLoader

In [4]:
train_ds=TensorDataset(inputs,targets)
train_ds[0:3]

(tensor([[ 73.,  67.,  43.],
         [ 91.,  88.,  64.],
         [ 87., 134.,  58.]]),
 tensor([[ 56.,  70.],
         [ 81., 101.],
         [119., 133.]]))

In [5]:
batch_size=5
train_dl=DataLoader(train_ds, batch_size, shuffle=True)

In [6]:
for xb,yb in train_dl:
  print(xb)
  print(yb)
  break

tensor([[ 68.,  96.,  71.],
        [ 73.,  67.,  43.],
        [ 87., 135.,  57.],
        [102.,  43.,  37.],
        [ 68.,  97.,  70.]])
tensor([[104., 118.],
        [ 56.,  70.],
        [118., 134.],
        [ 22.,  37.],
        [102., 120.]])


In [7]:
model=nn.Linear(3,2)
print(model.weight)
print(model.bias)

Parameter containing:
tensor([[ 0.0645,  0.4958, -0.2460],
        [ 0.0073,  0.3416, -0.1158]], requires_grad=True)
Parameter containing:
tensor([ 0.2210, -0.1711], requires_grad=True)


In [8]:
list(model.parameters())

[Parameter containing:
 tensor([[ 0.0645,  0.4958, -0.2460],
         [ 0.0073,  0.3416, -0.1158]], requires_grad=True),
 Parameter containing:
 tensor([ 0.2210, -0.1711], requires_grad=True)]

In [9]:
preds=model(inputs)
preds

tensor([[27.5657, 18.2709],
        [33.9711, 23.1445],
        [57.9938, 39.5260],
        [19.0139, 10.9774],
        [35.0422, 25.0226],
        [27.1344, 17.9365],
        [33.2293, 22.6870],
        [57.8123, 39.4175],
        [19.4451, 11.3117],
        [34.7317, 24.8995],
        [26.8239, 17.8134],
        [33.5398, 22.8101],
        [58.7356, 39.9835],
        [19.3244, 11.1005],
        [35.4735, 25.3570]], grad_fn=<AddmmBackward0>)

In [10]:
import torch.nn.functional as F

In [11]:
loss_fn=F.mse_loss

In [12]:
loss=loss_fn(model(inputs), targets)
print(loss)

tensor(3833.3557, grad_fn=<MseLossBackward0>)


In [13]:
opt=torch.optim.SGD(model.parameters(), lr=1e-5)

In [14]:
def fit(num_epochs, model, loss_fn, opt, train_dl):
  for epoch in range(num_epochs):
    for xb,yb in train_dl:
      pred=model(xb)
      loss=loss_fn(pred, yb)
      loss.backward()
      opt.step()
      opt.zero_grad()
    if (epoch+1) % 10 ==0:
      print('Epoch [{}/{}], Loss: {:.4f}'.format(epoch+1 , num_epochs, loss.item()))

In [15]:
fit(100, model, loss_fn, opt , train_dl)

Epoch [10/100], Loss: 237.5013
Epoch [20/100], Loss: 167.1236
Epoch [30/100], Loss: 209.9924
Epoch [40/100], Loss: 66.6897
Epoch [50/100], Loss: 45.9406
Epoch [60/100], Loss: 78.2539
Epoch [70/100], Loss: 60.3104
Epoch [80/100], Loss: 62.2029
Epoch [90/100], Loss: 57.2213
Epoch [100/100], Loss: 36.1784


In [16]:
preds=model(inputs)
preds

tensor([[ 58.0411,  71.3854],
        [ 78.1440,  96.7954],
        [124.2925, 139.0050],
        [ 27.2619,  43.7936],
        [ 91.4509, 108.4829],
        [ 56.8339,  70.3391],
        [ 77.2720,  96.1782],
        [124.2181, 139.2484],
        [ 28.4691,  44.8399],
        [ 91.7861, 108.9120],
        [ 57.1691,  70.7682],
        [ 76.9368,  95.7491],
        [125.1645, 139.6222],
        [ 26.9267,  43.3645],
        [ 92.6581, 109.5292]], grad_fn=<AddmmBackward0>)

In [17]:
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 57.,  69.],
        [ 80., 102.],
        [118., 132.],
        [ 21.,  38.],
        [104., 118.],
        [ 57.,  69.],
        [ 82., 100.],
        [118., 134.],
        [ 20.,  38.],
        [102., 120.]])

In [18]:
model(torch.tensor([[75,63,44.]]))

tensor([[53.7523, 67.7223]], grad_fn=<AddmmBackward0>)