In [9]:
import numpy as np
import torch

In [10]:
inputs=np.array([[73,67,43],
                 [91,88,64],
                 [87,134,58],
                 [102,43,37],
                 [69,96,70]], dtype='float32')
print(inputs)

[[ 73.  67.  43.]
 [ 91.  88.  64.]
 [ 87. 134.  58.]
 [102.  43.  37.]
 [ 69.  96.  70.]]


In [11]:
targets=np.array([[56,70],
                  [81,101],
                  [119,133],
                  [22,37],
                  [103,119]], dtype='float32')
print(targets)

[[ 56.  70.]
 [ 81. 101.]
 [119. 133.]
 [ 22.  37.]
 [103. 119.]]


In [12]:
inputs=torch.from_numpy(inputs)
targets=torch.from_numpy(targets)
print(inputs)
print(targets)

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])
tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


In [16]:
w=torch.randn(2,3, requires_grad=True)
b=torch.randn(2 ,requires_grad=True)
print(w)
print(b)

tensor([[ 0.0852,  0.9319, -1.7855],
        [ 1.0809, -0.4196, -0.9462]], requires_grad=True)
tensor([ 0.4471, -0.9236], requires_grad=True)


In [17]:
def model(x):
  return x @ w.t()+b


In [19]:
preds=model(inputs)
print(preds)

tensor([[-7.6759e+00,  9.1816e+00],
        [-2.4069e+01, -4.4120e-02],
        [ 2.9168e+01, -1.7990e+01],
        [-1.6856e+01,  5.6273e+01],
        [-2.9203e+01, -3.2857e+01]], grad_fn=<AddBackward0>)


In [20]:
print(targets)

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


In [26]:
diff=preds-targets
torch.sum(diff * diff)/diff.numel()

tensor(10228.9795, grad_fn=<DivBackward0>)

In [28]:
def mse(t1 , t2):
  diff=t1-t2
  return torch.sum(diff * diff)/diff.numel()

In [29]:
loss=mse(preds,targets)
print(loss)

tensor(10228.9795, grad_fn=<DivBackward0>)


In [30]:
loss.backward()

In [31]:
print(w)
print(w.grad)

tensor([[ 0.0852,  0.9319, -1.7855],
        [ 1.0809, -0.4196, -0.9462]], requires_grad=True)
tensor([[-7022.0586, -7982.4199, -5072.9199],
        [-7056.6270, -9389.7656, -5551.2563]])


In [32]:
print(b)
print(b.grad)

tensor([ 0.4471, -0.9236], requires_grad=True)
tensor([-85.9271, -89.0872])


In [36]:
print(w)
w.grad

tensor([[ 0.0852,  0.9319, -1.7855],
        [ 1.0809, -0.4196, -0.9462]], requires_grad=True)


tensor([[-7022.0586, -7982.4199, -5072.9199],
        [-7056.6270, -9389.7656, -5551.2563]])

In [37]:
with torch.no_grad():
  w-=w.grad*1e-5
  b-=b.grad*1e-5

In [39]:
w, b

(tensor([[ 0.1554,  1.0117, -1.7348],
         [ 1.1514, -0.3257, -0.8907]], requires_grad=True),
 tensor([ 0.4479, -0.9227], requires_grad=True))

In [42]:
preds=model(inputs)
loss=mse(preds,targets)
print(loss)

tensor(7427.3086, grad_fn=<DivBackward0>)


In [44]:
w.grad.zero_()
b.grad.zero_()
print(w.grad)
print(b.grad)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([0., 0.])


In [50]:
for i in range(500):
  preds=model(inputs)
  loss=mse(preds,targets)
  loss.backward()
  with torch.no_grad():
    w-=w.grad*1e-5
    b-=b.grad*1e-5
    w.grad.zero_()
    b.grad.zero_()

In [51]:
preds=model(inputs)
loss=mse(preds,targets)
print(loss)

tensor(85.0739, grad_fn=<DivBackward0>)


In [52]:
preds

tensor([[ 58.1810,  70.8486],
        [ 74.4926,  95.8138],
        [134.6060, 143.1329],
        [ 25.6982,  40.5255],
        [ 85.8955, 108.4584]], grad_fn=<AddBackward0>)

In [53]:
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])